from euclid_macros import *
A = euPoint(40,300)
B = euPoint(37,-49)
C = euPoint(-200,-90)
D = euPoint(-200, 100)
seac.color("blue")
AB = euLine(A,B)
seac.color("green")
BC = euLine(B,C)
seac.color("red")
CA = euLine(C,A)
perp = perpendicular(D,AB)
bisect = angle_bisector(A,B,C)
bisect2 = angle_bisector(B,A,C,show_process=True)
#bisect3 = angle_bisector(B,C,A, show_process=True)
turtle.exitonclick()