from euCLId import *

A = euPoint(-300, 0)
B = euPoint(300,0)
D = euPoint(-200,0)

AB = euLine(A,B)
perpAB_D = perpendicular(D,AB)

E = euPoint(-175,0)
F = euPoint(-100, 0)
G = euPoint(-50,0)
H = euPoint(0,0)
I = euPoint(50,0)
J = euPoint(75,0)
K = euPoint(200,0)
L = euPoint(250,0)

circAE = euCircle(midpoint(A,E), A)
circAF = euCircle(midpoint(A,F), A)
circAG = euCircle(midpoint(A,G), A)
circAH = euCircle(midpoint(A,H), A)
circAI = euCircle(midpoint(A,I), A)
circAJ = euCircle(midpoint(A,J), A)
circAK = euCircle(midpoint(A,K), A)
circAL = euCircle(midpoint(A,L), A)

seac.color("blue")
M1, M2 = intersect(circAE, perpAB_D)
N1, N2 = intersect(circAF, perpAB_D)
O1, O2 = intersect(circAG, perpAB_D)
P1, P2 = intersect(circAH, perpAB_D)
Q1, Q2 = intersect(circAI, perpAB_D)
R1, R2 = intersect(circAJ, perpAB_D)
S1, S2 = intersect(circAK, perpAB_D)
T1, T2 = intersect(circAL, perpAB_D)

seac.color("green")
perpM1, perpM2 = perpendicular(M1, perpAB_D), perpendicular(M2, perpAB_D)
perpN1, perpN2 = perpendicular(N1, perpAB_D), perpendicular(N2, perpAB_D)
perpO1, perpO2 = perpendicular(O1, perpAB_D), perpendicular(O2, perpAB_D)
perpP1, perpP2 = perpendicular(P1, perpAB_D), perpendicular(P2, perpAB_D)
perpQ1, perpQ2 = perpendicular(Q1, perpAB_D), perpendicular(Q2, perpAB_D)
perpR1, perpR2 = perpendicular(R1, perpAB_D), perpendicular(R2, perpAB_D)
perpS1, perpS2 = perpendicular(S1, perpAB_D), perpendicular(S2, perpAB_D)
perpT1, perpT2 = perpendicular(T1, perpAB_D), perpendicular(T2, perpAB_D)

turtle.exitonclick()